version: "3.9"
services:
    engine:
        build: ./engine
        ports:
            - "18989:18989"
            - "23324:23324"
            - "6969:6969"
            - "5001:5001"
    matching:
        build: ./matching
        ports:
            - "8000:80"
        environment:
            - MAX_WORKERS=1
    engine-client:
        build: ./engine-client
        ports:
            - "8500:8500"
